PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>

SELECT ?type_name ?unit
WHERE {
    ?unit 
        schema:name ?name ;
        a ?type .
    ?type rdfs:label ?type_label .
    BIND(concat(?type_label, "-", ?name) AS ?type_name)
    FILTER ( lang(?type_label) = "de" )
}
ORDER BY ?unit